version: "3.8"

services:
  # https://docs.localstack.cloud/getting-started/installation/#docker-compose
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack_main}"
    image: localstack/localstack:${LOCALSTACK_DOCKER_TAG:-2.1.0}
    ports:
      - "127.0.0.1:${PORT_WEB_UI:-8080}:${PORT_WEB_UI:-8080}"
      - "127.0.0.1:4566:4566"             # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"   # external services port range
    environment:
      - DEBUG=${DEBUG:-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=${START_WEB:-}
      #- KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - LOCALSTACK_HOST=localhost #"${LOCALSTACK_DOCKER_NAME:-localstack_main}"
    volumes:
      - ${LOCALSTACK_VOLUME_DIR:-./volume/localstack}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TMPDIR:-./volume/localstack-tmp}:/tmp/localstack
  
  mysql:
    image: mysql:8.1.0
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: test_admin
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_admin
      MYSQL_PASSWORD: test_admin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_VOLUME_DIR:-./volume/mysql/db}:/var/lib/mysql
      #- ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
